### ISSUE TITLE
Interesting, but unclear how to use

### ISSUE THREAD

**Issue by jdtsmith** [naofireblade/homebridge-logic#6]
This seems like a very interesting idea with a lot of potential, but I couldn't really get it to work.  I've been using statefuldummy switches to do basic logic: like indicate if a scene is active to use as a conditional for automations to run.  

Here's an example usage: when you see motion in the bedroom, turn on the hot water pump for 15m, but only if the Night Scene is not set (the is the dummy switch, turned on by the Night Scene and off by all other scenes).  For this you need both the Eve and Apple Home apps.  Eve lets you set multiple value conditionals (motion detected + dummy switch showing Night Scene off).  Home lets you create custom one-off scenes that you can turn off after a period of time (turn on the pump, turn off after 15 minutes).  So together, they can accomplish it. 

But I can see where timers and specifically date-based switches would be very useful.  For example: you could set a "vacation" variable that ends on a specific date, which can be used to disable various automations around the home until that date arrives.  I could probably do this with a "vacation" scene and a dummy switch (without the date-based switching).  But it will get complicated fast. 

In any case, a short tutorial with more information would be useful. I eventually discovered you can use the Eve app, go to Settings->Accessories->New Counter/Text/Timer, where you can add and rename variables.  But they don't then show up anywhere for use in Rules, for example.  I couldn't find out how to actually use these variables.   

Also, for counters, etc., are they implemented by HomeKit, or does your plugin actually perform the logic (increment/decrement the counters)?

Thanks for an interesting homebridge plugin.

**Comment by naofireblade** [comment]
Hi, this plugin provides devices ("New Counter/Timer/Switch/Text") that allow you to create more devices.

1. You have to open the desired "New ..." devices in the eve app
2. Tap on "Tap here" to change the name of your variable
3. Define the options like min/max for the counter
4. Switch on the "ADD" Switch
5. Go back and open the devices "My Variables".

There you will see your created variable. The logic for the counter, timer etc. is performed by the plugin itself.

I hope this helps, otherwise just ask again :) .

**Comment by cdecker22** [comment]
@naofireblade : I had the same impression (looks interesting, but unsure of how to use it).  I think you'd get a lot more usage of your plugin if you wrote some documentation, or even just posted some samples of how you're using the plugin.

Every night we say goodnight to our kids.  We let our daughter stay up for x minutes (usually about 20) before we flash her lights a few times to signal it's time to wrap it up, and then a few minutes later we turn off her lights.

I'd like to automate that whole process.  I thought I'd be able to set a timer for 20 minutes, and then use an automation somehow to give the warning, and then turn off the lights 2 minutes later.

Is this possible with your plugin.

**Comment by naofireblade** [comment]
Hey @cdecker22 ,
that's possible with the plugin but very inconvenient (especially the flashing part). And you are right the documentation and the features need more work. But I moved over to another home automation platform (home assistant) and therefore only have limited time to maintain my plugins.
The problem with homekit is that the automations are way to limited. To automate your use case even without flashing, you would need 3 different variables and 4 different automations. That's the reason why I moved on to home assistant.

So without flashing multiple times you could do it this way:

Variables:
- Timer sleep1 with 20 minutes
- Timer sleep2 with 2 minutes
- Timer flashTimer with 2 seconds

Automations (each bullet point is one automation):
- At 8:00pm turn on sleep1 and turn on light
- When sleep1 goes off, then turn light off and flashTimer on
- When flashTimer goes off, then turn light on and turn sleep2 on
- When sleep2 goes off, then turn light off
