### ISSUE TITLE
Not supported by Apple Home app

### ISSUE THREAD

**Issue by schwarzTass** [naofireblade/homebridge-logic#8]
After installing the plugin, additional fields (variables, etc.) are shown in HomeKit iOS12 but it says  "Not supported". 
![img_0350](https://user-images.githubusercontent.com/20500098/49341133-8ccb9d80-f649-11e8-9208-c68143e06f1a.jpg)

**Comment by naofireblade** [comment]
Hey, you will need the free homekit app [Eve](https://itunes.apple.com/de/app/elgato-eve/id917695792) because the apple homekit app does not support custom accessories.
